# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=200)),
                ('was_searched', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Basic')),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.WebsiteList'),
        ),
    ]
